// AUTO-GENERATED by scripts/sync-data.mjs — do not hand-edit data sourced from
// vLLM recipes (contextLength, variant precisions, recipe_id). Curated fields
// (benchmark, type, tested) are preserved across syncs. Weight-only vram is
// COMPUTED (totalParams x bytes-per-param) for pure precisions; mixed-precision
// values (MXFP4/compound like gpt-oss, "FP4+FP8", "AMD-FP8") stay curated.
// Last sync: 2026-07-13.
//
// SOURCES OF TRUTH (see README "Data Sources" / AGENTS.md):
//   model specs (params, context, arch) ........ recipes.vllm.ai/<id>.json -> .model.*
//   variant precisions + per-model VRAM hints ... same .variants.* (vram is KV-INCLUSIVE)
//   quant x GPU compatibility (GPU_QUANT_COMPAT)  vLLM quantization "supported hardware"
//                                                 docs + recipe variant descriptions
//   GPU hardware specs .......................... NVIDIA datasheets / recipe hardware_profile
// VRAM values here are WEIGHT-ONLY (no KV cache). usableVram = floor(physical * 0.95).
// GPU_QUANT_COMPAT is tri-state: 'native' (HW tensor cores) | 'sw' (vLLM software path).

const GPU_CONFIG = {
    "L4-24GB": {
        "vram": 24,
        "usableVram": 22,
        "architecture": "Ada Lovelace",
        "sm": "sm_89",
        "memory": "GDDR6",
        "name": "L4 24GB"
    },
    "A100-80GB": {
        "vram": 80,
        "usableVram": 76,
        "architecture": "Ampere",
        "sm": "sm_80",
        "memory": "HBM2e",
        "name": "A100 80GB"
    },
    "H100-80GB": {
        "vram": 80,
        "usableVram": 76,
        "architecture": "Hopper",
        "sm": "sm_90",
        "memory": "HBM3",
        "name": "H100 80GB"
    },
    "H200-141GB": {
        "vram": 141,
        "usableVram": 133,
        "architecture": "Hopper",
        "sm": "sm_90",
        "memory": "HBM3e",
        "name": "H200 141GB"
    },
    "B100-192GB": {
        "vram": 192,
        "usableVram": 182,
        "architecture": "Blackwell",
        "sm": "sm_100",
        "memory": "HBM3e",
        "name": "B100 192GB"
    },
    "B200-192GB": {
        "vram": 192,
        "usableVram": 182,
        "architecture": "Blackwell",
        "sm": "sm_100",
        "memory": "HBM3e",
        "name": "B200 192GB"
    }
};

const GPU_QUANT_COMPAT = {
    "L4-24GB": {
        "BF16": "native",
        "FP8": "native",
        "INT8": "native",
        "INT4": "sw",
        "MXFP4": "sw"
    },
    "A100-80GB": {
        "BF16": "native",
        "FP8": "sw",
        "INT8": "native",
        "INT4": "sw",
        "MXFP4": "sw"
    },
    "H100-80GB": {
        "BF16": "native",
        "FP8": "native",
        "INT8": "native",
        "INT4": "sw",
        "MXFP4": "sw"
    },
    "H200-141GB": {
        "BF16": "native",
        "FP8": "native",
        "INT8": "native",
        "INT4": "sw",
        "MXFP4": "sw"
    },
    "B100-192GB": {
        "BF16": "native",
        "FP8": "native",
        "INT8": "native",
        "INT4": "sw",
        "NVFP4": "native",
        "MXFP4": "native",
        "MXFP8": "native"
    },
    "B200-192GB": {
        "BF16": "native",
        "FP8": "native",
        "INT8": "native",
        "INT4": "sw",
        "NVFP4": "native",
        "MXFP4": "native",
        "MXFP8": "native"
    }
};

const MODELS_DATA = [
    { id: 1, name: "Kimi-K2.7-Code", provider: "moonshotai", params: "1T/32B", totalParams: 1000, activeParams: 32, prec: "INT4", vram: 500, variants: [{prec: "INT4", vram: 500, note: "GGUF via llama.cpp (not vLLM)"}], type: "vision", contextLength: 262144, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "moonshotai/Kimi-K2.7-Code", kvBytesPerToken: 70272 },
    { id: 2, name: "diffusiongemma-26B-A4B-it", provider: "Google", params: "26B/4B", totalParams: 26, activeParams: 4, prec: "BF16", vram: 52, variants: [{prec: "FP8", vram: 26}, {prec: "NVFP4", vram: 13}], type: "vision", contextLength: 262144, benchmark: {"mmlu":72.1,"humaneval":55.2,"math":48.3}, hf_url: "google/diffusiongemma-26B-A4B-it", kvBytesPerToken: 40960, recipe_id: "Google/diffusiongemma-26B-A4B-it" },
    { id: 3, name: "NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16", provider: "nvidia", params: "550B/55B", totalParams: 550, activeParams: 55, prec: "BF16", vram: 1100, variants: [{prec: "NVFP4", vram: 275}], type: "text", contextLength: 262144, benchmark: {"mmlu":85.2,"humaneval":82.1,"math":75.4}, hf_url: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16" },
    { id: 4, name: "MiniMax-M3", provider: "MiniMaxAI", params: "427B/26B", totalParams: 427, activeParams: 26, prec: "BF16", vram: 854, variants: [{prec: "MXFP8", vram: 427, note: "mi36x"}, {prec: "NVFP4", vram: 214, note: "synced from vLLM recipe"}, {prec: "MXFP4", vram: 214, note: "synced from vLLM recipe"}], type: "moe", contextLength: 1048576, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "MiniMaxAI/MiniMax-M3", kvBytesPerToken: 122880 },
    { id: 5, name: "Cosmos3-Super-Text2Image", provider: "nvidia", params: "64B", totalParams: 64, activeParams: 64, prec: "BF16", vram: 128, variants: [], type: "vision", contextLength: 262144, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "nvidia/Cosmos3-Super-Text2Image", kvBytesPerToken: 262144 },
    { id: 6, name: "Mellum2-12B-A2.5B-Thinking", provider: "JetBrains", params: "12B/2.5B", totalParams: 12, activeParams: 2.5, prec: "BF16", vram: 24, variants: [], type: "text", contextLength: 131072, benchmark: {"mmlu":68.4,"humaneval":45.2,"math":52.1}, hf_url: "JetBrains/Mellum2-12B-A2.5B-Thinking", kvBytesPerToken: 14336 },
    { id: 7, name: "Step-3.7-Flash", provider: "stepfun-ai", params: "198B/11B", totalParams: 198, activeParams: 11, prec: "BF16", vram: 396, variants: [{prec: "FP8", vram: 198}, {prec: "NVFP4", vram: 99, note: "synced from vLLM recipe"}], type: "moe", contextLength: 262144, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "stepfun-ai/Step-3.7-Flash", kvBytesPerToken: 393216 },
    { id: 8, name: "gemma-4-12B-it", provider: "Google", params: "12B", totalParams: 12, activeParams: 12, prec: "BF16", vram: 24, variants: [{prec: "W4A16", vram: 6}], type: "text", contextLength: 131072, benchmark: {"mmlu":76.8,"humaneval":52.4,"math":54.2,"mgsm":78.3}, hf_url: "google/gemma-4-12B-it", kvBytesPerToken: 65536, recipe_id: "Google/gemma-4-12B-it" },
    { id: 9, name: "Cosmos3-Super-Image2Video", provider: "nvidia", params: "64B", totalParams: 64, activeParams: 64, prec: "BF16", vram: 128, variants: [], type: "vision", contextLength: 262144, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "nvidia/Cosmos3-Super-Image2Video", kvBytesPerToken: 262144 },
    { id: 10, name: "MiniCPM5-1B", provider: "openbmb", params: "1.1B", totalParams: 1.1, activeParams: 1.1, prec: "BF16", vram: 2, variants: [], type: "text", contextLength: 131072, benchmark: {"mmlu":58.2,"humaneval":28.4,"math":32.1}, hf_url: "openbmb/MiniCPM5-1B", kvBytesPerToken: 24576 },
    { id: 11, name: "Intern-S2-Preview", provider: "internlm", params: "36B/3B", totalParams: 36, activeParams: 3, prec: "BF16", vram: 72, variants: [{prec: "FP8", vram: 36}], type: "moe", contextLength: 262144, benchmark: {"mmlu":72.5,"humaneval":48.2,"math":45.8}, hf_url: "internlm/Intern-S2-Preview", kvBytesPerToken: 20480 },
    { id: 17, name: "Laguna-XS.2", provider: "poolside", params: "33B/3B", totalParams: 33, activeParams: 3, prec: "BF16", vram: 66, variants: [{prec: "FP8", vram: 33, note: "synced from vLLM recipe"}, {prec: "NVFP4", vram: 17, note: "synced from vLLM recipe"}, {prec: "INT4", vram: 17, note: "synced from vLLM recipe"}], type: "moe", contextLength: 262144, benchmark: {"mmlu":70.4,"humaneval":55.8,"math":48.2}, hf_url: "poolside/Laguna-XS.2", kvBytesPerToken: 40960 },
    { id: 18, name: "DeepSeek-V4-Pro", provider: "deepseek-ai", params: "1600B/49B", totalParams: 1600, activeParams: 49, prec: "FP4+FP8", vram: 960, variants: [{prec: "NVFP4", vram: 800}, {prec: "FP8", vram: 1600, note: "synced from vLLM recipe"}], type: "moe", contextLength: 1048576, benchmark: {"mmlu":88.5,"humaneval":92.1,"math":86.4}, hf_url: "deepseek-ai/DeepSeek-V4-Pro", kvBytesPerToken: 124928 },
    { id: 19, name: "DeepSeek-V4-Flash", provider: "deepseek-ai", params: "284B/13B", totalParams: 284, activeParams: 13, prec: "FP4+FP8", vram: 170, variants: [{prec: "NVFP4", vram: 142, note: "Blackwell only"}, {prec: "FP8", vram: 284, note: "synced from vLLM recipe"}], type: "moe", contextLength: 1048576, benchmark: {"mmlu":87.2,"humaneval":90.5,"math":85.1}, hf_url: "deepseek-ai/DeepSeek-V4-Flash", kvBytesPerToken: 88064 },
    { id: 20, name: "Qwen3.6-27B", provider: "Qwen", params: "27B", totalParams: 27, activeParams: 27, prec: "BF16", vram: 54, variants: [{prec: "FP8", vram: 27}, {prec: "NVFP4", vram: 14, note: "synced from vLLM recipe"}], type: "text", contextLength: 262144, benchmark: {"mmlu":78.5,"humaneval":58.4,"math":52.3}, hf_url: "Qwen/Qwen3.6-27B", kvBytesPerToken: 65536 },
    { id: 21, name: "Nemotron-3-Nano-Omni-30B-A3B-Reasoning", provider: "nvidia", params: "31B/3B", totalParams: 31, activeParams: 3, prec: "BF16", vram: 62, variants: [{prec: "FP8", vram: 31}, {prec: "NVFP4", vram: 16}], type: "moe", contextLength: 262144, benchmark: {"mmlu":74.2,"humaneval":52.8,"math":58.4}, hf_url: "nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-BF16", kvBytesPerToken: 53248 },
    { id: 22, name: "Qwen3.6-35B-A3B", provider: "Qwen", params: "35B/3B", totalParams: 35, activeParams: 3, prec: "BF16", vram: 70, variants: [{prec: "FP8", vram: 35}, {prec: "NVFP4", vram: 18}], type: "moe", contextLength: 262144, benchmark: {"mmlu":79.2,"humaneval":62.1,"math":55.8}, hf_url: "Qwen/Qwen3.6-35B-A3B", kvBytesPerToken: 20480 },
    { id: 24, name: "MiniCPM-V-4.6", provider: "openbmb", params: "1.3B", totalParams: 1.3, activeParams: 1.3, prec: "BF16", vram: 3, variants: [], type: "vision", contextLength: 262144, benchmark: {"mmlu":62.4,"humaneval":35.2,"math":38.5}, hf_url: "openbmb/MiniCPM-V-4.6", kvBytesPerToken: 12288 },
    { id: 26, name: "MiniMax-M2.7", provider: "MiniMaxAI", params: "230B/10B", totalParams: 230, activeParams: 10, prec: "FP8", vram: 230, variants: [{prec: "NVFP4", vram: 115, note: "Blackwell only"}], type: "moe", contextLength: 196608, benchmark: {"mmlu":74.8,"humaneval":65.2,"math":58.4}, hf_url: "MiniMaxAI/MiniMax-M2.7", kvBytesPerToken: 253952, tested: true },
    { id: 30, name: "gemma-4-26B-A4B-it", provider: "Google", params: "26B/4B", totalParams: 26, activeParams: 4, prec: "BF16", vram: 52, variants: [{prec: "FP8", vram: 26}, {prec: "NVFP4", vram: 13}], type: "vision", contextLength: 131072, benchmark: {"mmlu":77.5,"humaneval":54.8,"math":49.2}, hf_url: "google/gemma-4-26B-A4B-it", kvBytesPerToken: 40960, recipe_id: "Google/gemma-4-26B-A4B-it" },
    { id: 31, name: "gemma-4-31B-it", provider: "Google", params: "31B", totalParams: 31, activeParams: 31, prec: "BF16", vram: 62, variants: [{prec: "FP8", vram: 31}, {prec: "NVFP4", vram: 16}, {prec: "W4A16", vram: 16}], type: "text", contextLength: 262144, benchmark: {"mmlu":78.6,"humaneval":48.8,"math":50,"mgsm":74.3}, hf_url: "google/gemma-4-31B-it", kvBytesPerToken: 163840, recipe_id: "Google/gemma-4-31B-it" },
    { id: 32, name: "Cosmos3-Nano", provider: "nvidia", params: "16B", totalParams: 16, activeParams: 16, prec: "BF16", vram: 32, variants: [], type: "vision", contextLength: 262144, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "nvidia/Cosmos3-Nano", kvBytesPerToken: 147456 },
    { id: 33, name: "Cosmos3-Super", provider: "nvidia", params: "64B", totalParams: 64, activeParams: 64, prec: "BF16", vram: 128, variants: [], type: "vision", contextLength: 262144, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "nvidia/Cosmos3-Super", kvBytesPerToken: 262144 },
    { id: 35, name: "NVIDIA-Nemotron-3-Nano-4B-BF16", provider: "nvidia", params: "4B", totalParams: 4, activeParams: 4, prec: "BF16", vram: 8, variants: [{prec: "FP8", vram: 4}], type: "text", contextLength: 262144, benchmark: {"mmlu":58.4,"humaneval":38.2,"math":32.5}, hf_url: "nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16", kvBytesPerToken: 172032 },
    { id: 36, name: "gemma-4-E2B-it", provider: "Google", params: "5B", totalParams: 5, activeParams: 5, prec: "BF16", vram: 10, variants: [{prec: "FP8", vram: 5}, {prec: "QAT-W4A16", vram: 3}, {prec: "QAT-mobile", vram: 2}], type: "text", contextLength: 131072, benchmark: {"mmlu":65.2,"humaneval":42.5,"math":38.4}, hf_url: "google/gemma-4-E2B-it", kvBytesPerToken: 7168, recipe_id: "Google/gemma-4-E2B-it" },
    { id: 37, name: "gemma-4-E4B-it", provider: "Google", params: "8B", totalParams: 8, activeParams: 8, prec: "BF16", vram: 16, variants: [{prec: "FP8", vram: 8}, {prec: "QAT-W4A16", vram: 4}, {prec: "QAT-mobile", vram: 3}], type: "text", contextLength: 131072, benchmark: {"mmlu":68.4,"humaneval":45.2,"math":42.1}, hf_url: "google/gemma-4-E4B-it", kvBytesPerToken: 14336, recipe_id: "Google/gemma-4-E4B-it" },
    { id: 38, name: "Qwen3.5-0.8B", provider: "Qwen", params: "0.8B", totalParams: 0.8, activeParams: 0.8, prec: "BF16", vram: 2, variants: [], type: "text", contextLength: 262144, benchmark: {"mmlu":52.4,"humaneval":28.5,"math":25.2}, hf_url: "Qwen/Qwen3.5-0.8B", kvBytesPerToken: 12288 },
    { id: 39, name: "Qwen3.5-2B", provider: "Qwen", params: "2B", totalParams: 2, activeParams: 2, prec: "BF16", vram: 4, variants: [], type: "text", contextLength: 262144, benchmark: {"mmlu":55.8,"humaneval":32.4,"math":28.6}, hf_url: "Qwen/Qwen3.5-2B", kvBytesPerToken: 12288 },
    { id: 40, name: "Qwen3.5-4B", provider: "Qwen", params: "4B", totalParams: 4, activeParams: 4, prec: "BF16", vram: 8, variants: [{prec: "FP8", vram: 4}], type: "text", contextLength: 262144, benchmark: {"mmlu":58.2,"humaneval":35.8,"math":32.4}, hf_url: "Qwen/Qwen3.5-4B", kvBytesPerToken: 32768 },
    { id: 41, name: "Qwen3.5-9B", provider: "Qwen", params: "9B", totalParams: 9, activeParams: 9, prec: "BF16", vram: 18, variants: [], type: "text", contextLength: 262144, benchmark: {"mmlu":65.4,"humaneval":42.8,"math":38.2}, hf_url: "Qwen/Qwen3.5-9B", kvBytesPerToken: 32768 },
    { id: 43, name: "Qwen3.5-27B", provider: "Qwen", params: "27B", totalParams: 27, activeParams: 27, prec: "BF16", vram: 54, variants: [{prec: "FP8", vram: 27}, {prec: "GPTQ-Int4", vram: 14}], type: "text", contextLength: 262144, benchmark: {"mmlu":75.8,"humaneval":52.4,"math":48.5}, hf_url: "Qwen/Qwen3.5-27B", kvBytesPerToken: 65536 },
    { id: 44, name: "Qwen3.5-35B-A3B", provider: "Qwen", params: "35B/3B", totalParams: 35, activeParams: 3, prec: "BF16", vram: 70, variants: [{prec: "FP8", vram: 35}, {prec: "GPTQ-Int4", vram: 18}], type: "moe", contextLength: 262144, benchmark: {"mmlu":77.2,"humaneval":55.4,"math":50.8}, hf_url: "Qwen/Qwen3.5-35B-A3B", kvBytesPerToken: 20480 },
    { id: 46, name: "MiniMax-M2.5", provider: "MiniMaxAI", params: "230B/10B", totalParams: 230, activeParams: 10, prec: "FP8", vram: 230, variants: [{prec: "NVFP4", vram: 115, note: "Blackwell only"}], type: "moe", contextLength: 196608, benchmark: {"mmlu":73.5,"humaneval":62.4,"math":56.2}, hf_url: "MiniMaxAI/MiniMax-M2.5", kvBytesPerToken: 253952 },
    { id: 47, name: "GLM-5.2", provider: "zai-org", params: "743B/39B", totalParams: 743, activeParams: 39, prec: "FP8", vram: 743, variants: [{prec: "BF16", vram: 1486}, {prec: "NVFP4", vram: 372, note: "synced from vLLM recipe"}], type: "moe", contextLength: 1048576, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "zai-org/GLM-5.2", kvBytesPerToken: 89856 },
    { id: 48, name: "GLM-5", provider: "zai-org", params: "744B/40B", totalParams: 744, activeParams: 40, prec: "BF16", vram: 1488, variants: [{prec: "FP8", vram: 744, note: "synced from vLLM recipe"}, {prec: "NVFP4", vram: 372, note: "synced from vLLM recipe"}], type: "moe", contextLength: 202752, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "zai-org/GLM-5", kvBytesPerToken: 89856 },
    { id: 49, name: "GLM-OCR", provider: "zai-org", params: "0.9B", totalParams: 0.9, activeParams: 0.9, prec: "BF16", vram: 2, variants: [], type: "embedding", contextLength: 131072, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "zai-org/GLM-OCR", kvBytesPerToken: 65536 },
    { id: 50, name: "PaddleOCR-VL-1.5", provider: "PaddlePaddle", params: "0.9B", totalParams: 0.9, activeParams: 0.9, prec: "BF16", vram: 2, variants: [], type: "embedding", contextLength: 131072, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "PaddlePaddle/PaddleOCR-VL-1.5", kvBytesPerToken: 18432 },
    { id: 51, name: "Qwen3-ASR-1.7B", provider: "Qwen", params: "2.3B", totalParams: 2.3, activeParams: 2.3, prec: "BF16", vram: 5, variants: [], type: "text", contextLength: 65536, benchmark: {"mmlu":54.2,"humaneval":null,"math":null}, hf_url: "Qwen/Qwen3-ASR-1.7B" },
    { id: 52, name: "DeepSeek-OCR-2", provider: "deepseek-ai", params: "3B", totalParams: 3, activeParams: 3, prec: "BF16", vram: 6, variants: [], type: "embedding", contextLength: 8192, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "deepseek-ai/DeepSeek-OCR-2", kvBytesPerToken: 61440 },
    { id: 53, name: "Mistral-Small-4-119B-2603", provider: "mistralai", params: "119B/6.5B", totalParams: 119, activeParams: 6.5, prec: "FP8", vram: 119, variants: [{prec: "NVFP4", vram: 60}], type: "moe", contextLength: 262144, benchmark: {"mmlu":82.4,"humaneval":75.2,"math":72.8}, hf_url: "mistralai/Mistral-Small-4-119B-2603", kvBytesPerToken: 23040 },
    { id: 54, name: "jina-embeddings-v5-text-small", provider: "jinaai", params: "0.7B", totalParams: 0.7, activeParams: 0.7, prec: "BF16", vram: 1, variants: [], type: "embedding", contextLength: 32768, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "jinaai/jina-embeddings-v5-text-small", kvBytesPerToken: 114688 },
    { id: 55, name: "Voxtral-Mini-4B-Realtime-2602", provider: "mistralai", params: "4.4B", totalParams: 4.4, activeParams: 4.4, prec: "BF16", vram: 9, variants: [], type: "text", contextLength: 131072, benchmark: {"mmlu":58.5,"humaneval":35.2,"math":32.4}, hf_url: "mistralai/Voxtral-Mini-4B-Realtime-2602", kvBytesPerToken: 106496 },
    { id: 56, name: "translategemma-27b-it", provider: "Google", params: "27B", totalParams: 27, activeParams: 27, prec: "BF16", vram: 54, variants: [{prec: "FP8", vram: 27}], type: "text", contextLength: 131072, benchmark: {"mmlu":74.2,"humaneval":48.5,"math":45.2}, hf_url: "google/translategemma-27b-it", recipe_id: "Google/translategemma-27b-it" },
    { id: 57, name: "GLM-Image", provider: "zai-org", params: "16B", totalParams: 16, activeParams: 16, prec: "BF16", vram: 32, variants: [], type: "vision", contextLength: 4096, benchmark: {"mmlu":68.4,"humaneval":45.2,"math":null}, hf_url: "zai-org/GLM-Image" },
    { id: 60, name: "MiniMax-M2.1", provider: "MiniMaxAI", params: "230B/10B", totalParams: 230, activeParams: 10, prec: "FP8", vram: 230, variants: [{prec: "NVFP4", vram: 115, note: "Blackwell only"}], type: "moe", contextLength: 196608, benchmark: {"mmlu":72.8,"humaneval":60.5,"math":54.2}, hf_url: "MiniMaxAI/MiniMax-M2.1", kvBytesPerToken: 253952 },
    { id: 62, name: "GLM-ASR-Nano-2512", provider: "zai-org", params: "2.3B", totalParams: 2.3, activeParams: 2.3, prec: "BF16", vram: 5, variants: [], type: "text", contextLength: 8192, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "zai-org/GLM-ASR-Nano-2512", kvBytesPerToken: 57344 },
    { id: 63, name: "GLM-4.6V", provider: "zai-org", params: "107B/12B", totalParams: 107, activeParams: 12, prec: "BF16", vram: 214, variants: [{prec: "FP8", vram: 107, note: "synced from vLLM recipe"}], type: "vision", contextLength: 131072, benchmark: {"mmlu":78.5,"humaneval":62.4,"math":null}, hf_url: "zai-org/GLM-4.6V", kvBytesPerToken: 188416 },
    { id: 64, name: "LongCat-Image-Edit", provider: "meituan-longcat", params: "6B", totalParams: 6, activeParams: 6, prec: "BF16", vram: 12, variants: [], type: "vision", contextLength: 8192, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "meituan-longcat/LongCat-Image-Edit" },
    { id: 65, name: "NVIDIA-Nemotron-3-Nano-30B-A3B-BF16", provider: "nvidia", params: "30B/3B", totalParams: 30, activeParams: 3, prec: "BF16", vram: 60, variants: [{prec: "FP8", vram: 30}], type: "moe", contextLength: 262144, benchmark: {"mmlu":72.4,"humaneval":48.5,"math":52.1}, hf_url: "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16", kvBytesPerToken: 53248 },
    { id: 70, name: "Ministral-3-14B-Instruct-2512", provider: "mistralai", params: "14B", totalParams: 14, activeParams: 14, prec: "FP8", vram: 14, variants: [{prec: "FP8", vram: 14}], type: "text", contextLength: 262144, benchmark: {"mmlu":68.4,"humaneval":45.2,"math":42.8}, hf_url: "mistralai/Ministral-3-14B-Instruct-2512", kvBytesPerToken: 163840 },
    { id: 71, name: "Ministral-3-8B-Reasoning-2512", provider: "mistralai", params: "8B", totalParams: 8, activeParams: 8, prec: "BF16", vram: 16, variants: [], type: "text", contextLength: 262144, benchmark: {"mmlu":65.2,"humaneval":42.5,"math":48.2}, hf_url: "mistralai/Ministral-3-8B-Reasoning-2512", kvBytesPerToken: 139264 },
    { id: 72, name: "Kimi-Linear-48B-A3B-Instruct", provider: "moonshotai", params: "48B/3B", totalParams: 48, activeParams: 3, prec: "BF16", vram: 96, variants: [], type: "moe", contextLength: 1048576, benchmark: {"mmlu":78.2,"humaneval":65.4,"math":58.5}, hf_url: "moonshotai/Kimi-Linear-48B-A3B-Instruct", kvBytesPerToken: 31104 },
    { id: 73, name: "Glyph", provider: "zai-org", params: "10B", totalParams: 10, activeParams: 10, prec: "BF16", vram: 20, variants: [], type: "text", contextLength: 131072, benchmark: {"mmlu":62.4,"humaneval":38.5,"math":null}, hf_url: "zai-org/Glyph", kvBytesPerToken: 40960 },
    { id: 74, name: "plamo-3-nict-31b-base", provider: "pfnet", params: "32B", totalParams: 32, activeParams: 32, prec: "BF16", vram: 64, variants: [], type: "text", contextLength: 4096, benchmark: {"mmlu":70.5,"humaneval":48.2,"math":45.8}, hf_url: "pfnet/plamo-3-nict-31b-base" },
    { id: 75, name: "MiniMax-M2", provider: "MiniMaxAI", params: "230B/10B", totalParams: 230, activeParams: 10, prec: "FP8", vram: 230, variants: [{prec: "NVFP4", vram: 115, note: "Blackwell only"}], type: "moe", contextLength: 196608, benchmark: {"mmlu":71.5,"humaneval":58.4,"math":52.3}, hf_url: "MiniMaxAI/MiniMax-M2", kvBytesPerToken: 253952 },
    { id: 76, name: "NVIDIA-Nemotron-Nano-12B-v2-VL-BF16", provider: "nvidia", params: "12B", totalParams: 12, activeParams: 12, prec: "BF16", vram: 24, variants: [{prec: "FP8", vram: 12}, {prec: "NVFP4-QAD", vram: 6}], type: "vision", contextLength: 131072, benchmark: {"mmlu":68.5,"humaneval":42.8,"math":38.2}, hf_url: "nvidia/NVIDIA-Nemotron-Nano-12B-v2-VL-BF16" },
    { id: 77, name: "DeepSeek-OCR", provider: "deepseek-ai", params: "3B", totalParams: 3, activeParams: 3, prec: "BF16", vram: 6, variants: [], type: "embedding", contextLength: 8192, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "deepseek-ai/DeepSeek-OCR", kvBytesPerToken: 61440 },
    { id: 78, name: "PaddleOCR-VL", provider: "PaddlePaddle", params: "0.9B", totalParams: 0.9, activeParams: 0.9, prec: "BF16", vram: 2, variants: [], type: "embedding", contextLength: 131072, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "PaddlePaddle/PaddleOCR-VL", kvBytesPerToken: 18432 },
    { id: 79, name: "Mistral-Medium-3.5-128B", provider: "mistralai", params: "128B", totalParams: 128, activeParams: 128, prec: "FP8", vram: 128, variants: [], type: "text", contextLength: 262144, benchmark: {"mmlu":82.4,"humaneval":72.5,"math":68.2}, hf_url: "mistralai/Mistral-Medium-3.5-128B", kvBytesPerToken: 360448 },
    { id: 82, name: "Qwen3Guard-Gen-8B", provider: "Qwen", params: "8B", totalParams: 8, activeParams: 8, prec: "BF16", vram: 16, variants: [], type: "text", contextLength: 32768, benchmark: {"mmlu":62.4,"humaneval":38.5,"math":35.2}, hf_url: "Qwen/Qwen3Guard-Gen-8B", kvBytesPerToken: 147456 },
    { id: 85, name: "InternVL3_5-8B", provider: "OpenGVLab", params: "8B", totalParams: 8, activeParams: 8, prec: "BF16", vram: 16, variants: [], type: "vision", contextLength: 40960, benchmark: {"mmlu":70.5,"humaneval":48.2,"math":null}, hf_url: "OpenGVLab/InternVL3_5-8B", kvBytesPerToken: 147456 },
    { id: 87, name: "Seed-OSS-36B-Instruct", provider: "ByteDance-Seed", params: "36B", totalParams: 36, activeParams: 36, prec: "BF16", vram: 72, variants: [], type: "text", contextLength: 524288, benchmark: {"mmlu":76.8,"humaneval":55.4,"math":52.1}, hf_url: "ByteDance-Seed/Seed-OSS-36B-Instruct", kvBytesPerToken: 262144 },
    { id: 88, name: "NVIDIA-Nemotron-Nano-9B-v2", provider: "nvidia", params: "9B", totalParams: 9, activeParams: 9, prec: "BF16", vram: 18, variants: [{prec: "FP8", vram: 9}, {prec: "NVFP4", vram: 5}], type: "text", contextLength: 131072, benchmark: {"mmlu":66.4,"humaneval":42.5,"math":38.8}, hf_url: "nvidia/NVIDIA-Nemotron-Nano-9B-v2", kvBytesPerToken: 229376 },
    { id: 90, name: "gpt-oss-20b", provider: "openai", params: "21B/3.6B", totalParams: 21, activeParams: 3.6, prec: "MXFP4", vram: 16, variants: [], type: "moe", contextLength: 131072, benchmark: {"mmlu":72.4,"humaneval":55.2,"math":52.8}, hf_url: "openai/gpt-oss-20b", kvBytesPerToken: 24576 },
    { id: 91, name: "gpt-oss-120b", provider: "openai", params: "120B/5.1B", totalParams: 120, activeParams: 5.1, prec: "MXFP4", vram: 63, variants: [{prec: "AMD-FP8", vram: 80}], type: "moe", contextLength: 131072, benchmark: {"mmlu":82.5,"humaneval":72.4,"math":68.5}, hf_url: "openai/gpt-oss-120b", kvBytesPerToken: 36864 },
    { id: 92, name: "Qwen-Image", provider: "Qwen", params: "20B", totalParams: 20, activeParams: 20, prec: "BF16", vram: 40, variants: [{prec: "FP8", vram: 20, note: "synced from vLLM recipe"}, {prec: "INT8", vram: 20, note: "synced from vLLM recipe"}], type: "vision", contextLength: 8192, benchmark: {"mmlu":68.2,"humaneval":null,"math":null}, hf_url: "Qwen/Qwen-Image" },
    { id: 93, name: "Wan2.2-T2V-A14B-Diffusers", provider: "Wan-AI", params: "28B/14B", totalParams: 28, activeParams: 14, prec: "BF16", vram: 56, variants: [], type: "vision", contextLength: 32768, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "Wan-AI/Wan2.2-T2V-A14B-Diffusers" },
    { id: 96, name: "Qwen3-235B-A22B-Instruct-2507", provider: "Qwen", params: "235B/22B", totalParams: 235, activeParams: 22, prec: "BF16", vram: 470, variants: [{prec: "FP8", vram: 235}, {prec: "NVFP4", vram: 118}], type: "moe", contextLength: 262144, benchmark: {"mmlu":87.2,"humaneval":85.4,"math":78.5}, hf_url: "Qwen/Qwen3-235B-A22B-Instruct-2507", kvBytesPerToken: 192512 },
    { id: 99, name: "ERNIE-4.5-21B-A3B-PT", provider: "baidu", params: "21B/3B", totalParams: 21, activeParams: 3, prec: "BF16", vram: 42, variants: [{prec: "300B-A47B", vram: null, note: "High memory variant"}], type: "moe", contextLength: 131072, benchmark: {"mmlu":74.5,"humaneval":52.4,"math":48.2}, hf_url: "baidu/ERNIE-4.5-21B-A3B-PT", kvBytesPerToken: 57344 },
    { id: 100, name: "ERNIE-4.5-VL-28B-A3B-PT", provider: "baidu", params: "28B/3B", totalParams: 28, activeParams: 3, prec: "BF16", vram: 56, variants: [{prec: "424B-A47B", vram: null, note: "VL variant"}, {prec: "FP8", vram: 28, note: "synced from vLLM recipe"}], type: "vision", contextLength: 131072, benchmark: {"mmlu":75.2,"humaneval":null,"math":null}, hf_url: "baidu/ERNIE-4.5-VL-28B-A3B-PT", kvBytesPerToken: 57344 },
    { id: 101, name: "Hunyuan-A13B-Instruct", provider: "tencent", params: "80B/13B", totalParams: 80, activeParams: 13, prec: "BF16", vram: 160, variants: [{prec: "FP8", vram: 80, note: "synced from vLLM recipe"}], type: "moe", contextLength: 32768, benchmark: {"mmlu":78.4,"humaneval":62.5,"math":58.2}, hf_url: "tencent/Hunyuan-A13B-Instruct", kvBytesPerToken: 131072 },
    { id: 103, name: "Qwen3-32B", provider: "Qwen", params: "32B", totalParams: 32, activeParams: 32, prec: "BF16", vram: 64, variants: [{prec: "FP8", vram: 32}, {prec: "AWQ", vram: 16}], type: "text", contextLength: 40960, benchmark: {"mmlu":76.8,"humaneval":55.4,"math":52.5}, hf_url: "Qwen/Qwen3-32B", kvBytesPerToken: 262144 },
    { id: 104, name: "Qwen3-4B", provider: "Qwen", params: "4B", totalParams: 4, activeParams: 4, prec: "BF16", vram: 8, variants: [{prec: "FP8", vram: 4}], type: "text", contextLength: 40960, benchmark: {"mmlu":58.4,"humaneval":35.2,"math":32.5}, hf_url: "Qwen/Qwen3-4B", kvBytesPerToken: 147456 },
    { id: 106, name: "jina-reranker-m0", provider: "jinaai", params: "2.4B", totalParams: 2.4, activeParams: 2.4, prec: "BF16", vram: 5, variants: [], type: "embedding", contextLength: 32768, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "jinaai/jina-reranker-m0", kvBytesPerToken: 28672 },
    { id: 107, name: "Phi-4-mini-instruct", provider: "microsoft", params: "4B", totalParams: 4, activeParams: 4, prec: "BF16", vram: 8, variants: [], type: "text", contextLength: 131072, benchmark: {"mmlu":62.4,"humaneval":38.5,"math":35.2}, hf_url: "microsoft/Phi-4-mini-instruct", kvBytesPerToken: 131072 },
    { id: 109, name: "Qwen2.5-VL-7B-Instruct", provider: "Qwen", params: "7B", totalParams: 7, activeParams: 7, prec: "BF16", vram: 14, variants: [{prec: "AWQ", vram: 4}], type: "vision", contextLength: 128000, benchmark: {"mmlu":68.4,"humaneval":42.5,"math":null}, hf_url: "Qwen/Qwen2.5-VL-7B-Instruct", kvBytesPerToken: 57344 },
    { id: 110, name: "DeepSeek-R1", provider: "deepseek-ai", params: "671B/37B", totalParams: 671, activeParams: 37, prec: "FP8", vram: 671, variants: [{prec: "FP8", vram: 671}, {prec: "NVFP4", vram: 336}], type: "moe", contextLength: 163840, benchmark: {"mmlu":90.5,"humaneval":96.2,"math":94.8}, hf_url: "deepseek-ai/DeepSeek-R1", kvBytesPerToken: 70272 },
    { id: 112, name: "Llama-3.3-70B-Instruct", provider: "meta-llama", params: "70B", totalParams: 70, activeParams: 70, prec: "BF16", vram: 140, variants: [{prec: "FP8", vram: 70}, {prec: "NVFP4", vram: 35}], type: "text", contextLength: 131072, benchmark: {"mmlu":86,"humaneval":88.4,"math":77,"mgsm":91.1}, hf_url: "meta-llama/Llama-3.3-70B-Instruct" },
    { id: 113, name: "stable-diffusion-3.5-medium", provider: "stabilityai", params: "2.5B", totalParams: 2.5, activeParams: 2.5, prec: "BF16", vram: 5, variants: [], type: "vision", contextLength: 8192, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "stabilityai/stable-diffusion-3.5-medium" },
    { id: 114, name: "Qwen2.5-32B", provider: "Qwen", params: "32B", totalParams: 32, activeParams: 32, prec: "BF16", vram: 64, variants: [], type: "text", contextLength: 131072, benchmark: {"mmlu":75.4,"humaneval":52.8,"math":48.2}, hf_url: "Qwen/Qwen2.5-32B", kvBytesPerToken: 262144 },
    { id: 115, name: "Llama-3.1-8B-Instruct", provider: "meta-llama", params: "8B", totalParams: 8, activeParams: 8, prec: "BF16", vram: 16, variants: [{prec: "FP8", vram: 8}, {prec: "NVFP4", vram: 4}], type: "text", contextLength: 131072, benchmark: {"mmlu":68.5,"humaneval":45.2,"math":42.8}, hf_url: "meta-llama/Llama-3.1-8B-Instruct" },
    { id: 116, name: "stable-audio-open-1.0", provider: "stabilityai", params: "1.2B", totalParams: 1.2, activeParams: 1.2, prec: "BF16", vram: 2, variants: [], type: "text", contextLength: 8192, benchmark: {"mmlu":null,"humaneval":null,"math":null}, hf_url: "stabilityai/stable-audio-open-1.0" },
    { id: 118, name: "GLM-GA", provider: "zai-org", params: "10B", totalParams: 10, activeParams: 10, prec: "BF16", vram: 20, variants: [], type: "text", contextLength: 131072, benchmark: {"mmlu":62.4,"humaneval":38.5,"math":35.2}, hf_url: "zai-org/GLM-GA" },
    { id: 119, name: "Mellum2-12B-A2.5B-Instruct", provider: "JetBrains", params: "12B/2.5B", totalParams: 12, activeParams: 2.5, prec: "BF16", vram: 24, variants: [], type: "text", contextLength: 131072, benchmark: {"mmlu":68.2,"humaneval":44.5,"math":48.5}, hf_url: "JetBrains/Mellum2-12B-A2.5B-Instruct", kvBytesPerToken: 14336 },
    { id: 120, name: "DeepSeek-V3", provider: "deepseek-ai", params: "671B/37B", totalParams: 671, activeParams: 37, prec: "FP8", vram: 671, variants: [{prec: "NVFP4", vram: 336, note: "Blackwell only"}], type: "moe", contextLength: 163840, benchmark: {}, hf_url: "deepseek-ai/DeepSeek-V3", kvBytesPerToken: 70272 },
    { id: 121, name: "DeepSeek-V3.1", provider: "deepseek-ai", params: "671B/37B", totalParams: 671, activeParams: 37, prec: "FP8", vram: 671, variants: [{prec: "NVFP4", vram: 336, note: "Blackwell only"}], type: "moe", contextLength: 163840, benchmark: {}, hf_url: "deepseek-ai/DeepSeek-V3.1", kvBytesPerToken: 70272 },
    { id: 122, name: "DeepSeek-V3.2", provider: "deepseek-ai", params: "671B/37B", totalParams: 671, activeParams: 37, prec: "FP8", vram: 671, variants: [{prec: "NVFP4", vram: 336, note: "Blackwell only"}], type: "moe", contextLength: 163840, benchmark: {}, hf_url: "deepseek-ai/DeepSeek-V3.2", kvBytesPerToken: 70272 },
    { id: 123, name: "DeepSeek-V3.2-Exp", provider: "deepseek-ai", params: "671B/37B", totalParams: 671, activeParams: 37, prec: "FP8", vram: 671, variants: [], type: "moe", contextLength: 163840, benchmark: {}, hf_url: "deepseek-ai/DeepSeek-V3.2-Exp", kvBytesPerToken: 70272 },
    { id: 124, name: "Qwen3-Coder-480B-A35B-Instruct", provider: "Qwen", params: "480B/35B", totalParams: 480, activeParams: 35, prec: "BF16", vram: 960, variants: [{prec: "FP8", vram: 480}, {prec: "NVFP4", vram: 240, note: "Blackwell only"}], type: "moe", contextLength: 262144, benchmark: {}, hf_url: "Qwen/Qwen3-Coder-480B-A35B-Instruct", kvBytesPerToken: 253952 },
    { id: 125, name: "Qwen3-Next-80B-A3B-Instruct", provider: "Qwen", params: "80B/3B", totalParams: 80, activeParams: 3, prec: "BF16", vram: 160, variants: [{prec: "FP8", vram: 80}, {prec: "NVFP4", vram: 40, note: "Blackwell only"}], type: "moe", contextLength: 262144, benchmark: {}, hf_url: "Qwen/Qwen3-Next-80B-A3B-Instruct", kvBytesPerToken: 98304 },
    { id: 126, name: "Qwen3-VL-235B-A22B-Instruct", provider: "Qwen", params: "235B/22B", totalParams: 235, activeParams: 22, prec: "BF16", vram: 470, variants: [{prec: "FP8", vram: 235}, {prec: "NVFP4", vram: 118, note: "Blackwell only"}], type: "vision", contextLength: 262144, benchmark: {}, hf_url: "Qwen/Qwen3-VL-235B-A22B-Instruct", kvBytesPerToken: 192512 },
    { id: 127, name: "Qwen3.5-122B-A10B", provider: "Qwen", params: "122B/10B", totalParams: 122, activeParams: 10, prec: "BF16", vram: 244, variants: [{prec: "FP8", vram: 122}, {prec: "GPTQ-Int4", vram: 61}], type: "moe", contextLength: 262144, benchmark: {}, hf_url: "Qwen/Qwen3.5-122B-A10B", kvBytesPerToken: 24576 },
    { id: 128, name: "Qwen3.5-397B-A17B", provider: "Qwen", params: "397B/17B", totalParams: 397, activeParams: 17, prec: "BF16", vram: 794, variants: [{prec: "NVFP4", vram: 199, note: "Blackwell only"}, {prec: "GPTQ-Int4", vram: 199}], type: "moe", contextLength: 262144, benchmark: {}, hf_url: "Qwen/Qwen3.5-397B-A17B", kvBytesPerToken: 30720 },
    { id: 129, name: "Qwen2.5-VL-72B-Instruct", provider: "Qwen", params: "72B", totalParams: 72, activeParams: 72, prec: "BF16", vram: 144, variants: [{prec: "AWQ", vram: 36}], type: "vision", contextLength: 128000, benchmark: {}, hf_url: "Qwen/Qwen2.5-VL-72B-Instruct", kvBytesPerToken: 327680 },
    { id: 130, name: "Llama-4-Scout-17B-16E-Instruct", provider: "meta-llama", params: "109B/17B", totalParams: 109, activeParams: 17, prec: "BF16", vram: 218, variants: [{prec: "FP8", vram: 109}, {prec: "NVFP4", vram: 55, note: "Blackwell only"}], type: "moe", contextLength: 10485760, benchmark: {}, hf_url: "meta-llama/Llama-4-Scout-17B-16E-Instruct" },
    { id: 131, name: "Mistral-Large-3-675B-Instruct-2512", provider: "mistralai", params: "675B/22B", totalParams: 675, activeParams: 22, prec: "FP8", vram: 675, variants: [{prec: "NVFP4", vram: 338}], type: "vision", contextLength: 294912, benchmark: {}, hf_url: "mistralai/Mistral-Large-3-675B-Instruct-2512" },
    { id: 132, name: "MiMo-V2.5-Pro", provider: "XiaomiMiMo", params: "1T/42B", totalParams: 1000, activeParams: 42, prec: "FP8", vram: 1000, variants: [], type: "moe", contextLength: 1048576, benchmark: {}, hf_url: "XiaomiMiMo/MiMo-V2.5-Pro", kvBytesPerToken: 430080 },
    { id: 133, name: "MiMo-V2-Flash", provider: "XiaomiMiMo", params: "309B/15B", totalParams: 309, activeParams: 15, prec: "FP8", vram: 309, variants: [], type: "moe", contextLength: 262144, benchmark: {}, hf_url: "XiaomiMiMo/MiMo-V2-Flash", kvBytesPerToken: 147456 },
    { id: 134, name: "MiMo-V2.5", provider: "XiaomiMiMo", params: "311B/15B", totalParams: 311, activeParams: 15, prec: "FP8", vram: 311, variants: [], type: "vision", contextLength: 1048576, benchmark: {}, hf_url: "XiaomiMiMo/MiMo-V2.5", kvBytesPerToken: 147456 },
    { id: 135, name: "Ling-2.6-1T", provider: "inclusionAI", params: "1T/50B", totalParams: 1000, activeParams: 50, prec: "FP8", vram: 1000, variants: [], type: "moe", contextLength: 262144, benchmark: {}, hf_url: "inclusionAI/Ling-2.6-1T", kvBytesPerToken: 92160 },
    { id: 136, name: "Ling-2.6-flash", provider: "inclusionAI", params: "104B/7.4B", totalParams: 104, activeParams: 7.4, prec: "BF16", vram: 208, variants: [], type: "moe", contextLength: 131072, benchmark: {}, hf_url: "inclusionAI/Ling-2.6-flash", kvBytesPerToken: 36864 },
    { id: 137, name: "Ring-1T-FP8", provider: "inclusionAI", params: "1T/50B", totalParams: 1000, activeParams: 50, prec: "FP8", vram: 1000, variants: [], type: "moe", contextLength: 65536, benchmark: {}, hf_url: "inclusionAI/Ring-1T-FP8", kvBytesPerToken: 327680 },
    { id: 138, name: "Ring-2.6-1T", provider: "inclusionAI", params: "1T/50B", totalParams: 1000, activeParams: 50, prec: "FP8", vram: 1000, variants: [], type: "moe", contextLength: 131072, benchmark: {}, hf_url: "inclusionAI/Ring-2.6-1T", kvBytesPerToken: 92160 },
    { id: 139, name: "Intern-S1", provider: "internlm", params: "241B/28B", totalParams: 241, activeParams: 28, prec: "BF16", vram: 482, variants: [{prec: "FP8", vram: 241}], type: "vision", contextLength: 65536, benchmark: {}, hf_url: "internlm/Intern-S1", kvBytesPerToken: 192512 },
    { id: 140, name: "Step-3.5-Flash", provider: "stepfun-ai", params: "196B/11B", totalParams: 196, activeParams: 11, prec: "BF16", vram: 392, variants: [{prec: "FP8", vram: 196}, {prec: "INT4", vram: 98}, {prec: "INT8", vram: 196, note: "synced from vLLM recipe"}], type: "moe", contextLength: 262144, benchmark: {}, hf_url: "stepfun-ai/Step-3.5-Flash", kvBytesPerToken: 393216 },
    { id: 141, name: "Kimi-K2-Instruct", provider: "moonshotai", params: "1T/32B", totalParams: 1000, activeParams: 32, prec: "FP8", vram: 1000, variants: [], type: "moe", contextLength: 131072, benchmark: {}, hf_url: "moonshotai/Kimi-K2-Instruct", kvBytesPerToken: 70272 },
    { id: 142, name: "Kimi-K2-Thinking", provider: "moonshotai", params: "1T/32B", totalParams: 1000, activeParams: 32, prec: "INT4", vram: 500, variants: [{prec: "NVFP4", vram: 500, note: "Blackwell only"}], type: "moe", contextLength: 262144, benchmark: {}, hf_url: "moonshotai/Kimi-K2-Thinking", kvBytesPerToken: 70272 },
    { id: 143, name: "Kimi-K2.5", provider: "moonshotai", params: "1T/32B", totalParams: 1000, activeParams: 32, prec: "INT4", vram: 500, variants: [{prec: "NVFP4", vram: 500, note: "Blackwell only"}], type: "vision", contextLength: 262144, benchmark: {}, hf_url: "moonshotai/Kimi-K2.5", kvBytesPerToken: 70272 },
];
